"use client";
import {useEffect,useMemo,useState} from "react";

const blank={id:null,name:"",recipe_type:"menu",category:"",status:"draft",yield_quantity:"",yield_unit:"g",prep_time_minutes:"",cook_time_minutes:"",kitchen_notes:"",components:[],steps:[],photos:[],versions:[]};
const photoTypes=[['prep','Prep'],['during','During'],['dine_in','Dine-in'],['takeaway','Takeaway'],['delivery','Delivery'],['final','Final']];

export default function Home(){
 const [data,setData]=useState({ingredients:[],recipes:[]});
 const [view,setView]=useState("home"),[q,setQ]=useState(""),[recipe,setRecipe]=useState(null),[addingIngredient,setAddingIngredient]=useState(false),[priceItem,setPriceItem]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [timerStart,setTimerStart]=useState(null),[elapsed,setElapsed]=useState(0);
 async function load(){setLoading(true);const r=await fetch('/api/bootstrap',{cache:'no-store'});const j=await r.json();setData(j.error?{ingredients:[],recipes:[]}:j);setLoading(false)}
 useEffect(()=>{load();if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 useEffect(()=>{if(!timerStart)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-timerStart)/1000)),1000);return()=>clearInterval(t)},[timerStart]);
 const recipes=useMemo(()=>data.recipes.filter(x=>(x.name+' '+(x.category||'')).toLowerCase().includes(q.toLowerCase())),[data.recipes,q]);
 const ingredients=useMemo(()=>data.ingredients.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[data.ingredients,q]);
 const approved=data.recipes.filter(x=>x.status==='approved').length,bulk=data.recipes.filter(x=>x.recipe_type==='bulk').length;
 const badge=s=><span className={'badge '+(s==='approved'?'ok':s==='draft'?'warn':'')}>{s||'draft'}</span>;
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 function newRecipe(){setRecipe({...blank,components:[],steps:[],photos:[],versions:[]});setElapsed(0);setTimerStart(null)}
 async function openRecipe(id){const r=await fetch('/api/recipes/'+id,{cache:'no-store'});const j=await r.json();if(!r.ok)return alert(j.error||'Could not load recipe');setRecipe({...blank,...j,components:(j.components||[]).map(c=>({kind:c.bulk_recipe_id?'bulk':'ingredient',id:c.bulk_recipe_id||c.ingredient_id,name:c.bulk_recipe_name||c.ingredient_name,quantity:Number(c.quantity),unit:c.unit,notes:c.notes||''})),steps:(j.steps||[]).map(s=>({instruction:s.instruction,duration_seconds:s.duration_seconds})),photos:j.photos||[],versions:j.versions||[]});setElapsed(0);setTimerStart(null)}
 async function saveIngredient(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/ingredients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error);setAddingIngredient(false);await load()}
 async function savePrice(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.ingredient_id=priceItem.id;const r=await fetch('/api/prices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error);setPriceItem(null);load()}
 async function saveRecipe(){if(!recipe.name.trim())return alert('Recipe name is required');setSaving(true);const url=recipe.id?'/api/recipes/'+recipe.id:'/api/recipes';const method=recipe.id?'PUT':'POST';const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(recipe)});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Could not save recipe');setRecipe(null);await load();setView('recipes')}
 function addComp(){const raw=document.getElementById('comp').value,qty=document.getElementById('qty').value,unit=document.getElementById('unit').value;if(!raw||!qty)return;const isBulk=raw.startsWith('bulk:');const id=raw.replace('bulk:','');const src=isBulk?data.recipes.find(x=>x.id===id):data.ingredients.find(x=>x.id===id);setRecipe({...recipe,components:[...recipe.components,{kind:isBulk?'bulk':'ingredient',id,name:src.name,quantity:Number(qty),unit}]});document.getElementById('qty').value=''}
 function addStep(){const instruction=document.getElementById('step').value.trim(),seconds=document.getElementById('secs').value;if(!instruction)return;setRecipe({...recipe,steps:[...recipe.steps,{instruction,duration_seconds:seconds?Number(seconds):null}]});document.getElementById('step').value='';document.getElementById('secs').value=''}
 async function compressPhoto(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
 async function addPhoto(e,type){const f=e.target.files?.[0];if(!f)return;const url=await compressPhoto(f);setRecipe(r=>({...r,photos:[...(r.photos||[]).filter(p=>p.photo_type!==type),{photo_type:type,storage_key:'inline:'+Date.now(),public_url:url,caption:''}]}));e.target.value=''}
 function removePhoto(type){setRecipe({...recipe,photos:recipe.photos.filter(p=>p.photo_type!==type)})}
 function useTimer(){setRecipe({...recipe,cook_time_minutes:Math.max(1,Math.round(elapsed/60))})}
 return <div className="shell"><header><div className="brand"><div className="logo">SG</div><div><h1>Recipe Lab</h1><div className="small">Salted Grills · Kitchen standardization</div></div></div></header><main>
 {loading?<div className="card">Loading kitchen data…</div>:<>
 {view==='home'&&<><div className="hero"><h2>Record first. Cost later.</h2><p>Capture the real kitchen process, bulk prep, yield, method, timing and presentation from your phone.</p><button className="primary" onClick={newRecipe}>＋ Start Recipe Trial</button></div><div className="stats"><div className="stat"><b>{data.ingredients.length}</b><span>Ingredients</span></div><div className="stat"><b>{data.recipes.length}</b><span>Recipes</span></div><div className="stat"><b>{bulk}</b><span>Bulk recipes</span></div><div className="stat"><b>{approved}</b><span>Approved</span></div></div><div className="titlebar"><h3>Continue working</h3><button className="textbtn" onClick={()=>setView('recipes')}>View all</button></div>{data.recipes.slice(0,5).map(r=><button className="card cardbtn" key={r.id} onClick={()=>openRecipe(r.id)}><div className="row"><div className="left"><div className="name">{r.recipe_type==='bulk'?'🧺':'🍽'} {r.name}</div><div className="meta">{r.category||'Uncategorized'} · v{r.version_no||1} · {r.component_count||0} components</div></div>{badge(r.status)}</div></button>)}</>}
 {view==='recipes'&&<><input className="search" placeholder="Search recipes…" value={q} onChange={e=>setQ(e.target.value)}/>{recipes.map(r=><button className="card cardbtn" key={r.id} onClick={()=>openRecipe(r.id)}><div className="row"><div className="left"><div className="name">{r.recipe_type==='bulk'?'🧺':'🍽'} {r.name}</div><div className="meta">{r.category||'Uncategorized'} · v{r.version_no||1} · {r.yield_quantity?`${r.yield_quantity} ${r.yield_unit}`:'Yield pending'}</div></div>{badge(r.status)}</div></button>)}<button className="primary wide" onClick={newRecipe}>＋ New Recipe</button></>}
 {view==='ingredients'&&<><input className="search" placeholder="Search ingredients…" value={q} onChange={e=>setQ(e.target.value)}/>{ingredients.map(i=><div className="card" key={i.id}><div className="row"><div><div className="name">{i.name}</div><div className="meta">{i.default_unit} · {i.latest_price?'Price available':'No price yet'}</div></div><button className="secondary" onClick={()=>setPriceItem(i)}>₨</button></div></div>)}<button className="primary wide" onClick={()=>setAddingIngredient(true)}>＋ Add Ingredient</button></>}
 {view==='costing'&&<><div className="notice">Costing stays separate from kitchen capture. Add prices when you are ready.</div><div className="titlebar"><h3>Ingredient Price Book</h3></div>{data.ingredients.map(i=><div className="card" key={i.id}><div className="row"><div><div className="name">{i.name}</div><div className="meta">{i.latest_price?`Rs ${Number(i.latest_price.purchase_price).toLocaleString()} / ${i.latest_price.purchase_quantity} ${i.latest_price.purchase_unit}`:'No purchase price'}</div></div><button className="secondary" onClick={()=>setPriceItem(i)}>{i.latest_price?'Update':'Add price'}</button></div></div>)}</>}
 </>}</main><nav><div className="navin">{[['home','⌂','Home'],['recipes','☷','Recipes'],['ingredients','◫','Ingredients'],['costing','₨','Costing']].map(([v,ic,l])=><button className={'nav '+(view===v?'active':'')} key={v} onClick={()=>{setView(v);setQ('')}}><strong>{ic}</strong>{l}</button>)}</div></nav>
 {recipe&&<div className="overlay"><div className="sheet"><div className="handle"/><div className="row"><div><h2>{recipe.id?'Edit Recipe':'Recipe Trial'}</h2><div className="small">{recipe.id?`Saving creates a new version after v${recipe.version_no||1}`:'No costing required here.'}</div></div><button className="secondary compact" onClick={()=>setRecipe(null)}>✕</button></div>
 <div className="timer"><div><span>Kitchen timer</span><b>{fmt(elapsed)}</b></div><div className="timeractions">{timerStart?<button className="secondary" onClick={()=>setTimerStart(null)}>Pause</button>:<button className="secondary" onClick={()=>setTimerStart(Date.now()-elapsed*1000)}>{elapsed?'Resume':'Start'}</button>}<button className="secondary" onClick={()=>{setTimerStart(null);setElapsed(0)}}>Reset</button><button className="primary" onClick={useTimer}>Use time</button></div></div>
 <label>Recipe type</label><div className="two"><button className={recipe.recipe_type==='menu'?'primary':'secondary'} onClick={()=>setRecipe({...recipe,recipe_type:'menu'})}>🍽 Menu Item</button><button className={recipe.recipe_type==='bulk'?'primary':'secondary'} onClick={()=>setRecipe({...recipe,recipe_type:'bulk'})}>🧺 Bulk Recipe</button></div><label>Name</label><input value={recipe.name} onChange={e=>setRecipe({...recipe,name:e.target.value})} placeholder="e.g. Boiled Rice"/><label>Category</label><input value={recipe.category||''} onChange={e=>setRecipe({...recipe,category:e.target.value})} placeholder="Rice, Burgers, Sauces…"/>
 <div className="titlebar"><h3>Ingredients / Bulk Prep</h3><button className="textbtn" onClick={()=>setAddingIngredient(true)}>＋ New ingredient</button></div>{recipe.components.map((c,n)=><div className="line" key={n}><div><b>{c.kind==='bulk'?'🧺 ':''}{c.name}</b><div className="small">{c.quantity} {c.unit}</div></div><button onClick={()=>setRecipe({...recipe,components:recipe.components.filter((_,i)=>i!==n)})}>×</button></div>)}<div className="three"><select id="comp"><option value="">Select…</option><optgroup label="Raw ingredients">{data.ingredients.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</optgroup><optgroup label="Bulk recipes">{data.recipes.filter(r=>r.recipe_type==='bulk'&&r.id!==recipe.id).map(r=><option key={r.id} value={'bulk:'+r.id}>{r.name}</option>)}</optgroup></select><input id="qty" inputMode="decimal" type="number" step="0.01" placeholder="Qty"/><select id="unit"><option>g</option><option>kg</option><option>ml</option><option>L</option><option>pc</option><option>portion</option></select></div><button className="secondary wide top8" onClick={addComp}>Add Component</button>
 <div className="titlebar"><h3>Method</h3></div>{recipe.steps.map((s,n)=><div className="line" key={n}><div><b>{n+1}. {s.instruction}</b><div className="small">{s.duration_seconds?`${s.duration_seconds} sec`:''}</div></div><button onClick={()=>setRecipe({...recipe,steps:recipe.steps.filter((_,i)=>i!==n)})}>×</button></div>)}<div className="two"><input id="step" placeholder="Cooking step"/><input id="secs" inputMode="numeric" type="number" placeholder="Seconds"/></div><button className="secondary wide top8" onClick={addStep}>Add Step</button>
 <div className="two"><div><label>Usable yield</label><input inputMode="decimal" type="number" step="0.01" value={recipe.yield_quantity||''} onChange={e=>setRecipe({...recipe,yield_quantity:e.target.value})}/></div><div><label>Unit</label><select value={recipe.yield_unit||'g'} onChange={e=>setRecipe({...recipe,yield_unit:e.target.value})}><option>g</option><option>kg</option><option>ml</option><option>L</option><option>portion</option></select></div></div><div className="two"><div><label>Prep minutes</label><input inputMode="numeric" type="number" value={recipe.prep_time_minutes||''} onChange={e=>setRecipe({...recipe,prep_time_minutes:e.target.value})}/></div><div><label>Cook minutes</label><input inputMode="numeric" type="number" value={recipe.cook_time_minutes||''} onChange={e=>setRecipe({...recipe,cook_time_minutes:e.target.value})}/></div></div>
 <div className="titlebar"><h3>Kitchen Photos</h3><span className="small">Tap to use camera</span></div><div className="photos">{photoTypes.map(([type,label])=>{const p=(recipe.photos||[]).find(x=>x.photo_type===type);return <label className={'photo '+(p?'hasphoto':'')} key={type}>{p?<><img src={p.public_url} alt={label}/><button type="button" onClick={e=>{e.preventDefault();removePhoto(type)}}>×</button></>:<><span>📷</span><small>{label}</small></>}<input type="file" accept="image/*" capture="environment" onChange={e=>addPhoto(e,type)}/></label>})}</div>
 <label>Kitchen notes</label><textarea value={recipe.kitchen_notes||''} onChange={e=>setRecipe({...recipe,kitchen_notes:e.target.value})} placeholder="Flame, soaking, texture, chef notes, packing instructions…"/><label>Status</label><select value={recipe.status||'draft'} onChange={e=>setRecipe({...recipe,status:e.target.value})}><option value="draft">Draft / Trial</option><option value="recorded">Recipe Recorded</option><option value="approved">Approved Standard</option></select>
 {recipe.versions?.length>0&&<><div className="titlebar"><h3>Version history</h3></div><div className="history">{recipe.versions.map(v=><div key={v.id}><b>v{v.version_no}</b><span>{v.status} · {new Date(v.created_at).toLocaleDateString()}</span></div>)}</div></>}
 <div className="actions stickyactions"><button className="secondary" onClick={()=>setRecipe(null)}>Cancel</button><button className="primary" disabled={saving} onClick={saveRecipe}>{saving?'Saving…':recipe.id?'Save New Version':'Save Recipe'}</button></div></div></div>}
 {addingIngredient&&<div className="overlay topmodal"><form className="sheet mini" onSubmit={saveIngredient}><div className="handle"/><div className="row"><h2>Add Ingredient</h2><button type="button" className="secondary compact" onClick={()=>setAddingIngredient(false)}>✕</button></div><label>Name</label><input name="name" required autoFocus/><div className="two"><div><label>Default unit</label><select name="default_unit"><option>g</option><option>kg</option><option>ml</option><option>L</option><option>pc</option></select></div><div><label>Type</label><select name="ingredient_type"><option value="raw">Raw</option><option value="prepared">Prepared</option></select></div></div><label>Notes</label><textarea name="notes"/><button className="primary wide top8">Save Ingredient</button></form></div>}
 {priceItem&&<div className="overlay"><form className="sheet mini" onSubmit={savePrice}><div className="handle"/><div className="row"><div><h2>Add Purchase Price</h2><div className="small">{priceItem.name}</div></div><button type="button" className="secondary compact" onClick={()=>setPriceItem(null)}>✕</button></div><div className="two"><div><label>Purchase quantity</label><input name="purchase_quantity" inputMode="decimal" type="number" step="0.01" required/></div><div><label>Unit</label><select name="purchase_unit"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pc</option></select></div></div><label>Purchase price (PKR)</label><input name="purchase_price" inputMode="decimal" type="number" step="0.01" required/><label>Price date</label><input name="price_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><label>Supplier (optional)</label><input name="supplier"/><button className="primary wide top8">Save Price</button></form></div>}
 </div>
}
