"use client";
import {useEffect,useMemo,useState} from "react";

const blank={id:null,name:"",recipe_type:"menu",category:"",status:"draft",yield_quantity:"",yield_unit:"g",prep_time_minutes:"",cook_time_minutes:"",kitchen_notes:"",components:[],steps:[],photos:[],versions:[]};
const photoTypes=[['prep','Prep'],['during','During'],['dine_in','Dine-in'],['takeaway','Takeaway'],['delivery','Delivery'],['final','Final']];
const editorSteps=[['basics','Basics'],['ingredients','Ingredients'],['method','Method'],['finish','Finish']];

export default function Home(){
 const [data,setData]=useState({ingredients:[],recipes:[]});
 const [view,setView]=useState('home'),[q,setQ]=useState(''),[recipe,setRecipe]=useState(null),[editorStep,setEditorStep]=useState('basics');
 const [addingIngredient,setAddingIngredient]=useState(false),[priceItem,setPriceItem]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [timerStart,setTimerStart]=useState(null),[elapsed,setElapsed]=useState(0);
 async function load(){setLoading(true);const r=await fetch('/api/bootstrap',{cache:'no-store'});const j=await r.json();setData(j.error?{ingredients:[],recipes:[]}:j);setLoading(false)}
 useEffect(()=>{load();if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 useEffect(()=>{if(!timerStart)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-timerStart)/1000)),1000);return()=>clearInterval(t)},[timerStart]);
 const recipes=useMemo(()=>data.recipes.filter(x=>(x.name+' '+(x.category||'')).toLowerCase().includes(q.toLowerCase())),[data.recipes,q]);
 const ingredients=useMemo(()=>data.ingredients.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())),[data.ingredients,q]);
 const approved=data.recipes.filter(x=>x.status==='approved').length, bulk=data.recipes.filter(x=>x.recipe_type==='bulk').length;
 const badge=s=><span className={'status '+(s==='approved'?'status-ok':s==='recorded'?'status-blue':'status-draft')}>{s==='approved'?'Approved':s==='recorded'?'Recorded':'Draft'}</span>;
 const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
 function newRecipe(){setRecipe({...blank,components:[],steps:[],photos:[],versions:[]});setEditorStep('basics');setElapsed(0);setTimerStart(null)}
 async function openRecipe(id){const r=await fetch('/api/recipes/'+id,{cache:'no-store'});const j=await r.json();if(!r.ok)return alert(j.error||'Could not load recipe');setRecipe({...blank,...j,components:(j.components||[]).map(c=>({kind:c.bulk_recipe_id?'bulk':'ingredient',id:c.bulk_recipe_id||c.ingredient_id,name:c.bulk_recipe_name||c.ingredient_name,quantity:Number(c.quantity),unit:c.unit,notes:c.notes||''})),steps:(j.steps||[]).map(s=>({instruction:s.instruction,duration_seconds:s.duration_seconds})),photos:j.photos||[],versions:j.versions||[]});setEditorStep('basics');setElapsed(0);setTimerStart(null)}
 async function saveIngredient(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/ingredients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error);setAddingIngredient(false);await load()}
 async function savePrice(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.ingredient_id=priceItem.id;const r=await fetch('/api/prices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return alert(j.error);setPriceItem(null);await load()}
 async function saveRecipe(){if(!recipe.name.trim()){setEditorStep('basics');return alert('Recipe name is required')}setSaving(true);const url=recipe.id?'/api/recipes/'+recipe.id:'/api/recipes',method=recipe.id?'PUT':'POST';const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(recipe)});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Could not save recipe');setRecipe(null);await load();setView('recipes')}
 function addComp(){const raw=document.getElementById('comp').value,qty=document.getElementById('qty').value,unit=document.getElementById('unit').value;if(!raw||!qty)return;const isBulk=raw.startsWith('bulk:'),id=raw.replace('bulk:','');const src=isBulk?data.recipes.find(x=>x.id===id):data.ingredients.find(x=>x.id===id);setRecipe({...recipe,components:[...recipe.components,{kind:isBulk?'bulk':'ingredient',id,name:src.name,quantity:Number(qty),unit}]});document.getElementById('qty').value=''}
 function addStep(){const instruction=document.getElementById('step').value.trim(),seconds=document.getElementById('secs').value;if(!instruction)return;setRecipe({...recipe,steps:[...recipe.steps,{instruction,duration_seconds:seconds?Number(seconds):null}]});document.getElementById('step').value='';document.getElementById('secs').value=''}
 async function compressPhoto(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
 async function addPhoto(e,type){const f=e.target.files?.[0];if(!f)return;const url=await compressPhoto(f);setRecipe(r=>({...r,photos:[...(r.photos||[]).filter(p=>p.photo_type!==type),{photo_type:type,storage_key:'inline:'+Date.now(),public_url:url,caption:''}]}));e.target.value=''}
 function removePhoto(type){setRecipe({...recipe,photos:recipe.photos.filter(p=>p.photo_type!==type)})}
 function useTimer(){setRecipe({...recipe,cook_time_minutes:Math.max(1,Math.round(elapsed/60))})}
 function goStep(dir){const i=editorSteps.findIndex(x=>x[0]===editorStep);setEditorStep(editorSteps[Math.max(0,Math.min(editorSteps.length-1,i+dir))][0])}
 const recipeCard=r=><button className="recipe-card" key={r.id} onClick={()=>openRecipe(r.id)}><div className="recipe-icon">{r.recipe_type==='bulk'?'B':'M'}</div><div className="recipe-info"><div className="recipe-name">{r.name}</div><div className="recipe-meta">{r.category||'Uncategorized'} · v{r.version_no||1} · {r.component_count||0} items</div></div>{badge(r.status)}<span className="chev">›</span></button>;
 return <div className="app-shell">
  <header className="app-header"><div className="brand"><div className="logo">SG</div><div><h1>Recipe Lab</h1><p>Kitchen standards</p></div></div><button className="header-action" onClick={newRecipe}>＋ Recipe</button></header>
  <main className="app-main">
   {loading?<div className="loading-card">Loading kitchen data…</div>:<>
    {view==='home'&&<>
      <section className="welcome"><div><span className="eyebrow">SALTED GRILLS</span><h2>Build recipes your kitchen can repeat.</h2><p>Capture the process first. Cost it when you are ready.</p></div><button className="welcome-btn" onClick={newRecipe}>Start recipe <span>→</span></button></section>
      <section className="metric-row"><div><b>{data.ingredients.length}</b><span>Ingredients</span></div><div><b>{data.recipes.length}</b><span>Recipes</span></div><div><b>{bulk}</b><span>Bulk</span></div><div><b>{approved}</b><span>Approved</span></div></section>
      <div className="section-head"><div><span>RECENT</span><h3>Continue working</h3></div><button onClick={()=>setView('recipes')}>See all</button></div>
      <div className="recipe-list">{data.recipes.length?data.recipes.slice(0,6).map(recipeCard):<div className="empty-state"><div>🍳</div><b>No recipes yet</b><p>Start with one dish being prepared today.</p><button onClick={newRecipe}>Create first recipe</button></div>}</div>
    </>}
    {view==='recipes'&&<><div className="page-title"><span>RECIPE LIBRARY</span><h2>Recipes</h2><p>Menu items and bulk preparations in one place.</p></div><div className="search-wrap">⌕<input placeholder="Search recipes" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="recipe-list">{recipes.map(recipeCard)}</div><button className="floating-add" onClick={newRecipe}>＋</button></>}
    {view==='ingredients'&&<><div className="page-title"><span>MASTER LIST</span><h2>Ingredients</h2><p>Add the kitchen items first. Pricing can come later.</p></div><div className="search-wrap">⌕<input placeholder="Search ingredients" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="ingredient-list">{ingredients.map(i=><div className="ingredient-card" key={i.id}><div className="ingredient-avatar">{i.name.slice(0,1).toUpperCase()}</div><div><b>{i.name}</b><span>{i.default_unit} · {i.latest_price?'Price available':'No price yet'}</span></div><button onClick={()=>setPriceItem(i)}>₨</button></div>)}</div><button className="floating-add" onClick={()=>setAddingIngredient(true)}>＋</button></>}
    {view==='costing'&&<><div className="page-title"><span>MANAGEMENT</span><h2>Costing</h2><p>Separate from kitchen capture so chefs never need to stop for prices.</p></div><div className="cost-note"><b>Costing stays optional.</b><span>Update purchase prices here and recipe costs can be calculated later.</span></div><div className="ingredient-list">{data.ingredients.map(i=><div className="ingredient-card" key={i.id}><div className="ingredient-avatar">₨</div><div><b>{i.name}</b><span>{i.latest_price?`Rs ${Number(i.latest_price.purchase_price).toLocaleString()} / ${i.latest_price.purchase_quantity} ${i.latest_price.purchase_unit}`:'No purchase price'}</span></div><button onClick={()=>setPriceItem(i)}>{i.latest_price?'Edit':'Add'}</button></div>)}</div></>}
   </>}
  </main>
  {!recipe&&!addingIngredient&&!priceItem&&<nav className="bottom-nav">{[['home','⌂','Home'],['recipes','☷','Recipes'],['ingredients','◫','Ingredients'],['costing','₨','Costing']].map(([v,ic,l])=><button className={view===v?'active':''} key={v} onClick={()=>{setView(v);setQ('')}}><strong>{ic}</strong><span>{l}</span></button>)}</nav>}

  {recipe&&<div className="workspace">
    <header className="workspace-head"><button className="workspace-close" onClick={()=>setRecipe(null)}>‹</button><div><span>{recipe.id?'EDIT RECIPE':'NEW RECIPE'}</span><h2>{recipe.name||'Untitled recipe'}</h2></div><div className="workspace-version">{recipe.id?'v'+(recipe.version_no||1):'Draft'}</div></header>
    <div className="stepper">{editorSteps.map(([k,l],i)=><button key={k} className={editorStep===k?'active':''} onClick={()=>setEditorStep(k)}><i>{i+1}</i><span>{l}</span></button>)}</div>
    <div className="workspace-body">
      {editorStep==='basics'&&<section className="editor-section"><div className="editor-intro"><span>STEP 1</span><h3>What are we preparing?</h3><p>Start with the identity of the recipe. Nothing financial is required here.</p></div><div className="choice-grid"><button className={recipe.recipe_type==='menu'?'choice active':''} onClick={()=>setRecipe({...recipe,recipe_type:'menu'})}><span>🍽️</span><b>Menu item</b><small>Sold directly to a customer</small></button><button className={recipe.recipe_type==='bulk'?'choice active':''} onClick={()=>setRecipe({...recipe,recipe_type:'bulk'})}><span>🧺</span><b>Bulk recipe</b><small>Used inside other recipes</small></button></div><div className="field"><label>Recipe name</label><input autoFocus value={recipe.name} onChange={e=>setRecipe({...recipe,name:e.target.value})} placeholder="e.g. Chicken Fried Rice"/></div><div className="field"><label>Category</label><input value={recipe.category||''} onChange={e=>setRecipe({...recipe,category:e.target.value})} placeholder="e.g. Rice, Burgers, Sauces"/></div>{recipe.versions?.length>0&&<div className="version-box"><b>Version history</b>{recipe.versions.slice(0,4).map(v=><div key={v.id}><span>v{v.version_no}</span><small>{v.status} · {new Date(v.created_at).toLocaleDateString()}</small></div>)}</div>}</section>}
      {editorStep==='ingredients'&&<section className="editor-section"><div className="editor-intro"><span>STEP 2</span><h3>What goes into it?</h3><p>Add raw ingredients or a prepared bulk recipe, with the exact quantity used.</p></div>{recipe.components.length>0&&<div className="component-list">{recipe.components.map((c,n)=><div className="component" key={n}><div className="component-order">{n+1}</div><div><b>{c.name}</b><span>{c.kind==='bulk'?'Bulk recipe':'Ingredient'}</span></div><strong>{c.quantity} {c.unit}</strong><button onClick={()=>setRecipe({...recipe,components:recipe.components.filter((_,i)=>i!==n)})}>×</button></div>)}</div>}<div className="add-box"><div className="field"><label>Ingredient or bulk recipe</label><select id="comp"><option value="">Select an item</option><optgroup label="Ingredients">{data.ingredients.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</optgroup><optgroup label="Bulk recipes">{data.recipes.filter(r=>r.recipe_type==='bulk'&&r.id!==recipe.id).map(r=><option key={r.id} value={'bulk:'+r.id}>{r.name}</option>)}</optgroup></select></div><div className="qty-grid"><div className="field"><label>Quantity</label><input id="qty" inputMode="decimal" type="number" step="0.01" placeholder="0"/></div><div className="field"><label>Unit</label><select id="unit"><option>g</option><option>kg</option><option>ml</option><option>L</option><option>pc</option><option>portion</option></select></div></div><button className="add-line" onClick={addComp}>＋ Add to recipe</button><button className="inline-link" onClick={()=>setAddingIngredient(true)}>Ingredient missing? Add it now</button></div></section>}
      {editorStep==='method'&&<section className="editor-section"><div className="editor-intro"><span>STEP 3</span><h3>How is it made?</h3><p>Record the method in the exact order another chef should follow.</p></div><div className="timer-card"><div><span>LIVE KITCHEN TIMER</span><b>{fmt(elapsed)}</b></div><div>{timerStart?<button onClick={()=>setTimerStart(null)}>Pause</button>:<button onClick={()=>setTimerStart(Date.now()-elapsed*1000)}>{elapsed?'Resume':'Start timer'}</button>}<button onClick={()=>{setTimerStart(null);setElapsed(0)}}>Reset</button><button className="timer-use" onClick={useTimer}>Use as cook time</button></div></div>{recipe.steps.length>0&&<div className="method-list">{recipe.steps.map((s,n)=><div className="method-step" key={n}><div>{n+1}</div><p><b>{s.instruction}</b>{s.duration_seconds?<span>{s.duration_seconds} sec</span>:null}</p><button onClick={()=>setRecipe({...recipe,steps:recipe.steps.filter((_,i)=>i!==n)})}>×</button></div>)}</div>}<div className="add-box"><div className="field"><label>Instruction</label><input id="step" placeholder="e.g. Heat wok on high flame"/></div><div className="field compact-field"><label>Time in seconds <small>(optional)</small></label><input id="secs" inputMode="numeric" type="number" placeholder="45"/></div><button className="add-line" onClick={addStep}>＋ Add next step</button></div></section>}
      {editorStep==='finish'&&<section className="editor-section"><div className="editor-intro"><span>STEP 4</span><h3>Finish the standard.</h3><p>Record yield, timing, presentation and any final kitchen notes.</p></div><div className="summary-grid"><div className="field"><label>Usable yield</label><input inputMode="decimal" type="number" step="0.01" value={recipe.yield_quantity||''} onChange={e=>setRecipe({...recipe,yield_quantity:e.target.value})} placeholder="0"/></div><div className="field"><label>Yield unit</label><select value={recipe.yield_unit||'g'} onChange={e=>setRecipe({...recipe,yield_unit:e.target.value})}><option>g</option><option>kg</option><option>ml</option><option>L</option><option>portion</option></select></div><div className="field"><label>Prep minutes</label><input inputMode="numeric" type="number" value={recipe.prep_time_minutes||''} onChange={e=>setRecipe({...recipe,prep_time_minutes:e.target.value})} placeholder="0"/></div><div className="field"><label>Cook minutes</label><input inputMode="numeric" type="number" value={recipe.cook_time_minutes||''} onChange={e=>setRecipe({...recipe,cook_time_minutes:e.target.value})} placeholder="0"/></div></div><div className="photo-head"><div><b>Presentation photos</b><span>Tap a tile to open the phone camera.</span></div></div><div className="photo-grid">{photoTypes.map(([type,label])=>{const p=(recipe.photos||[]).find(x=>x.photo_type===type);return <label className={'photo-tile '+(p?'filled':'')} key={type}>{p?<><img src={p.public_url} alt={label}/><button type="button" onClick={e=>{e.preventDefault();removePhoto(type)}}>×</button><small>{label}</small></>:<><span>＋</span><b>{label}</b></>}<input type="file" accept="image/*" capture="environment" onChange={e=>addPhoto(e,type)}/></label>})}</div><div className="field"><label>Kitchen notes</label><textarea value={recipe.kitchen_notes||''} onChange={e=>setRecipe({...recipe,kitchen_notes:e.target.value})} placeholder="Flame level, soaking time, texture, plating or packing notes…"/></div><div className="field"><label>Recipe status</label><select value={recipe.status||'draft'} onChange={e=>setRecipe({...recipe,status:e.target.value})}><option value="draft">Draft / Trial</option><option value="recorded">Recipe Recorded</option><option value="approved">Approved Standard</option></select></div></section>}
    </div>
    <footer className="workspace-footer"><button className="foot-secondary" disabled={editorStep==='basics'} onClick={()=>goStep(-1)}>Back</button>{editorStep!=='finish'?<button className="foot-primary" onClick={()=>goStep(1)}>Continue <span>→</span></button>:<button className="foot-primary" disabled={saving} onClick={saveRecipe}>{saving?'Saving…':recipe.id?'Save new version':'Save recipe'}</button>}</footer>
  </div>}

  {addingIngredient&&<div className="form-screen"><header><button onClick={()=>setAddingIngredient(false)}>‹</button><div><span>MASTER LIST</span><h2>Add ingredient</h2></div></header><form onSubmit={saveIngredient}><div className="form-intro"><div>＋</div><h3>New kitchen ingredient</h3><p>You can add pricing later. Only the kitchen information is needed now.</p></div><div className="field"><label>Ingredient name</label><input name="name" required autoFocus placeholder="e.g. Basmati Rice"/></div><div className="summary-grid"><div className="field"><label>Default unit</label><select name="default_unit"><option>g</option><option>kg</option><option>ml</option><option>L</option><option>pc</option></select></div><div className="field"><label>Type</label><select name="ingredient_type"><option value="raw">Raw ingredient</option><option value="prepared">Prepared item</option></select></div></div><div className="field"><label>Notes <small>(optional)</small></label><textarea name="notes" placeholder="Brand, grade, storage note…"/></div><button className="form-submit">Save ingredient</button></form></div>}

  {priceItem&&<div className="form-screen"><header><button onClick={()=>setPriceItem(null)}>‹</button><div><span>COSTING</span><h2>{priceItem.name}</h2></div></header><form onSubmit={savePrice}><div className="form-intro money"><div>₨</div><h3>Add purchase price</h3><p>This updates management costing only. It does not change the kitchen recipe.</p></div><div className="summary-grid"><div className="field"><label>Purchase quantity</label><input name="purchase_quantity" type="number" step="0.01" required placeholder="0"/></div><div className="field"><label>Purchase unit</label><select name="purchase_unit"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pc</option></select></div></div><div className="field"><label>Purchase price (PKR)</label><input name="purchase_price" type="number" step="0.01" required placeholder="0"/></div><div className="field"><label>Price date</label><input name="price_date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Supplier <small>(optional)</small></label><input name="supplier" placeholder="Supplier name"/></div><button className="form-submit">Save purchase price</button></form></div>}
 </div>
}
