"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {usePathname} from "next/navigation";
import "./shelfsense-snapshots.css";

const money=n=>Number.isFinite(Number(n))?`Rs ${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—';
const qty=n=>Number.isFinite(Number(n))?Number(n).toLocaleString(undefined,{maximumFractionDigits:3}):'—';
const pct=n=>Number.isFinite(Number(n))?`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`:'—';
const norm=v=>String(v||'').trim().toLowerCase();
function unitInfo(unit){const u=norm(unit);if(u==='kg')return['weight',1000,'g'];if(['g','gm','gram','grams'].includes(u))return['weight',1,'g'];if(['l','ltr','liter','litre'].includes(u))return['volume',1000,'ml'];if(u==='ml')return['volume',1,'ml'];if(['pc','pcs','piece','pieces','each','portion','portions'].includes(u))return['count',1,'pc'];return[u||'other',1,u||'other']}
function baseQty(q,u){return Number(q||0)*unitInfo(u)[1]}
function parseMeta(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)||{}}catch{return{}}}
function currentRate(i){const p=i?.latest_price;if(!p||p.costing_status==='needs_yield')return null;const info=unitInfo(p.purchase_unit),base=Number(p.purchase_quantity||0)*info[1];return base>0?Number(p.purchase_price)/base:null}
function menuPayload(bootstrap,preview){
  const ingredients=bootstrap?.ingredients||[],recipes=bootstrap?.recipes||[],prepared=recipes.filter(r=>r.recipe_type==='bulk'),menus=recipes.filter(r=>r.recipe_type==='menu');
  const current=new Map(),candidate=new Map();
  ingredients.forEach(i=>{const rate=currentRate(i);if(Number.isFinite(rate)){const x={rate,group:unitInfo(i.default_unit)[0],unit:unitInfo(i.default_unit)[2]};current.set(String(i.id),x);candidate.set(String(i.id),x)}});
  (preview?.rows||[]).forEach(r=>{if(Number.isFinite(Number(r.costingRate))){candidate.set(String(r.ingredientId),{rate:Number(r.costingRate),group:unitInfo(r.costingUnit)[0],unit:r.costingUnit})}});
  const recipeMap=new Map(recipes.map(r=>[String(r.id),r]));
  function cost(r,rates,stack=[]){if(!r||stack.includes(String(r.id)))return NaN;let total=0;for(const c of r.components_summary||[]){let v=NaN;if(c.ingredient_id){const x=rates.get(String(c.ingredient_id)),g=unitInfo(c.unit);if(x&&x.group===g[0])v=x.rate*baseQty(c.quantity,c.unit)}else if(c.bulk_recipe_id){const b=recipeMap.get(String(c.bulk_recipe_id)),bc=cost(b,rates,[...stack,String(r.id)]);if(Number.isFinite(bc)&&Number(b?.yield_quantity)>0&&unitInfo(b.yield_unit)[0]===unitInfo(c.unit)[0])v=bc*(baseQty(c.quantity,c.unit)/baseQty(b.yield_quantity,b.yield_unit))}if(!Number.isFinite(v))return NaN;total+=v}return total}
  return menus.map(r=>{const c=cost(r,candidate),old=cost(r,current),m=parseMeta(r.kitchen_notes),selling=Number(m.selling_price||0),target=Number(m.target_food_cost||35),food=selling>0&&Number.isFinite(c)?c/selling*100:null,contribution=selling>0&&Number.isFinite(c)?selling-c:null,status=!Number.isFinite(c)?'incomplete':selling>0&&c>=selling?'negative':food<=target?'healthy':food<=target+5?'watch':'critical';return{recipeId:r.id,name:r.name,category:r.category||'',cost:Number.isFinite(c)?c:0,complete:Number.isFinite(c),previousCost:Number.isFinite(old)?old:null,sellingPrice:selling||null,foodCostPercent:food,contribution,targetFoodCost:target,status,changePct:Number.isFinite(c)&&Number.isFinite(old)&&old>0?(c-old)/old*100:null}})
}

export default function ShelfSenseSnapshotOperations(){
  const path=usePathname()||'';
  const [target,setTarget]=useState(null),[open,setOpen]=useState(false),[tab,setTab]=useState('review');
  const [integration,setIntegration]=useState(null),[bootstrap,setBootstrap]=useState(null),[preview,setPreview]=useState(null),[history,setHistory]=useState([]);
  const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');

  useEffect(()=>{if(!path.startsWith('/purchase-prices')){setTarget(null);return}let stopped=false,tries=0;const find=()=>{if(stopped)return;const el=document.querySelector('.v2-head .v2-actions');if(el)return setTarget(el);if(tries++<180)requestAnimationFrame(find)};find();return()=>{stopped=true}},[path]);
  async function refresh(){setLoading(true);setMessage('');try{const [i,b,p,h]=await Promise.all([fetch('/api/integrations/shelfsense',{cache:'no-store'}).then(r=>r.json()),fetch('/api/bootstrap',{cache:'no-store'}).then(r=>r.json()),fetch('/api/integrations/shelfsense/sync',{cache:'no-store'}).then(r=>r.json()),fetch('/api/costing-snapshots',{cache:'no-store'}).then(r=>r.json())]);setIntegration(i);setBootstrap(b);setPreview(p);setHistory(h.snapshots||[])}catch(e){setMessage(e.message||'Could not load ShelfSense data')}setLoading(false)}
  useEffect(()=>{if(open)refresh()},[open]);

  const rows=useMemo(()=>{let a=preview?.rows||[];const q=search.trim().toLowerCase();if(q)a=a.filter(r=>`${r.ingredientName||''} ${r.supplier||''} ${r.purchaseUnit||''} ${r.sourceBaseUnit||''}`.toLowerCase().includes(q));if(filter==='changed')a=a.filter(r=>r.changed);if(filter==='up')a=a.filter(r=>Number(r.changePct)>0.0001);if(filter==='down')a=a.filter(r=>Number(r.changePct)<-0.0001);if(filter==='yield')a=a.filter(r=>r.needsYieldSetup);if(filter==='same')a=a.filter(r=>!r.changed);return a},[preview,search,filter]);
  const summary=preview?.summary||{};
  const active=history.find(x=>x.status==='published');
  const latestDraft=history.find(x=>x.status==='draft');

  async function saveYield(row,value){if(!(Number(value)>0))return;setBusy(true);const r=await fetch('/api/costing-conversions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredient_id:row.ingredientId,purchase_unit:row.yieldSourceUnit||row.sourceBaseUnit||row.purchaseUnit,usable_quantity:Number(value),costing_unit:row.yieldCostingUnit||row.costingUnit,source:'shelfsense'})}),j=await r.json();setMessage(r.ok?'Yield saved. ShelfSense review refreshed.':(j.error||'Could not save yield'));await refresh();setBusy(false)}

  async function createSnapshot(){setBusy(true);setMessage('');const menus=menuPayload(bootstrap,preview);const ingredientRows=(preview?.rows||[]).filter(r=>r.ingredientId&&r.purchaseUnit).map(r=>({ingredientId:r.ingredientId,ingredientName:r.ingredientName,purchaseQuantity:r.purchaseQuantity,purchaseUnit:r.purchaseUnit,purchasePrice:r.purchasePrice,supplier:r.supplier,priceDate:r.priceDate,sourceExternalId:r.sourceExternalId,storageUnit:r.sourceBaseUnit,storageUnitCost:r.sourceUnitCost,kitchenCost:r.costingRate,costingUnit:r.costingUnit,previousKitchenCost:r.previousCostingRate,changePct:r.changePct,direction:r.changePct==null?'new':r.changePct>0.0001?'up':r.changePct< -0.0001?'down':'flat',changed:Boolean(r.changed),needsYield:Boolean(r.needsYieldSetup),yieldSourceUnit:r.yieldSourceUnit,yieldUsableQuantity:r.yieldUsableQuantity,yieldCostingUnit:r.yieldCostingUnit,conversionWarning:Boolean(r.conversionWarning),sourcePurchaseUnit:r.sourcePurchaseUnit,sourcePurchaseFactor:r.sourcePurchaseFactor,sourceIssueUnit:r.sourceIssueUnit,sourceIssueFactor:r.sourceIssueFactor,sourceEnteredQty:r.sourceEnteredQty,sourceEnteredUnit:r.sourceEnteredUnit,sourceBaseQty:r.sourceBaseQty,sourceReceiptTotal:r.sourceReceiptTotal,effectiveDate:r.effectiveDate}));const s={mapped:ingredientRows.length,changed:ingredientRows.filter(x=>x.changed).length,increased:ingredientRows.filter(x=>x.direction==='up').length,decreased:ingredientRows.filter(x=>x.direction==='down').length,unchanged:ingredientRows.filter(x=>x.direction==='flat').length,needsYield:ingredientRows.filter(x=>x.needsYield).length,menuCritical:menus.filter(x=>x.status==='critical'||x.status==='negative').length,menuWatch:menus.filter(x=>x.status==='watch').length,menuHealthy:menus.filter(x=>x.status==='healthy').length,menuIncomplete:menus.filter(x=>x.status==='incomplete').length};const r=await fetch('/api/costing-snapshots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',asOf:preview?.asOf,ingredients:ingredientRows,menus,summary:s})}),j=await r.json();setMessage(r.ok?'Review snapshot created. Live costing has not changed.':(j.error||'Could not create snapshot'));await refresh();if(r.ok)setTab('history');setBusy(false)}
  async function snapshotAction(id,action){setBusy(true);const r=await fetch('/api/costing-snapshots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,snapshot_id:id})}),j=await r.json();setMessage(r.ok?(action==='publish'?'Costing published and is now active.':'Historical costing restored as active.'):(j.error||'Action failed'));await refresh();setBusy(false)}
  async function setManual(ingredientId){setBusy(true);const r=await fetch('/api/integrations/shelfsense/mappings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredient_id:ingredientId,source_type:'manual'})});const j=await r.json();setMessage(r.ok?'Ingredient switched to manual pricing.':(j.error||'Could not change mapping'));await refresh();setBusy(false)}

  if(!target)return null;const trigger=createPortal(<button className="ghost" onClick={()=>setOpen(true)}>Sync ShelfSense</button>,target);if(!open)return trigger;
  return <>{trigger}{createPortal(<div className="pcs-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="pcs-modal">
    <header className="pcs-head"><div><span>SHELFSENSE</span><h2>Cost Sync & Review</h2><p>Sync creates a report only. Your active PlateCost costing changes only after you publish a reviewed snapshot.</p></div><button onClick={()=>setOpen(false)}>×</button></header>
    <div className="pcs-tabs"><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}>Review</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Costing History {history.length>0&&<b>{history.length}</b>}</button><button className={tab==='mapping'?'active':''} onClick={()=>setTab('mapping')}>Mappings</button></div>
    <div className="pcs-body">{loading?<div className="pcs-empty">Loading ShelfSense…</div>:<>
      <div className="pcs-status"><div><small>ACTIVE COSTING</small><b>{active?new Date(active.snapshot_date).toLocaleDateString():'Current live data'}</b><span>{active?'Published snapshot':'No published snapshot yet'}</span></div><div><small>LATEST REVIEW</small><b>{latestDraft?new Date(latestDraft.snapshot_date).toLocaleDateString():'—'}</b><span>{latestDraft?'Draft · not published':'No draft review'}</span></div><div><small>CHANGED</small><b>{summary.changed||0}</b><span>{summary.increased||0} up · {summary.decreased||0} down</span></div><div><small>NEEDS YIELD</small><b>{summary.needsYield||0}</b><span>Resolve before publish</span></div></div>
      {message&&<div className="pcs-message">{message}</div>}
      {tab==='review'&&<><div className="pcs-review-top"><div><h3>Latest ShelfSense position</h3><p>Compare today's known costs with the active PlateCost values. Creating a snapshot does not update live costing.</p></div><button className="primary" disabled={busy||!preview?.rows?.length} onClick={createSnapshot}>{busy?'Working…':'Create Review Snapshot'}</button></div><div className="pcs-filterbar"><input placeholder="Search ingredient, supplier or unit…" value={search} onChange={e=>setSearch(e.target.value)}/><div>{[['all','All'],['changed','Changed'],['up','↑ Increased'],['down','↓ Decreased'],['yield','Needs yield'],['same','Unchanged']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{l}</button>)}</div></div><div className="pcs-table"><div className="pcs-row pcs-th"><span>Ingredient</span><span>ShelfSense storage cost</span><span>Active cost</span><span>Change</span><span>Yield</span><span>Status</span></div>{rows.map(r=><ReviewRow key={r.ingredientId} row={r} busy={busy} onYield={saveYield} onManual={setManual}/>)}</div></>}
      {tab==='history'&&<History snapshots={history} busy={busy} onAction={snapshotAction}/>} 
      {tab==='mapping'&&<Mappings integration={integration} bootstrap={bootstrap} busy={busy} onManual={setManual}/>} 
    </>}</div>
  </div></div>,document.body)}</>;
}

function ReviewRow({row:r,busy,onYield,onManual}){const [y,setY]=useState(r.yieldUsableQuantity?String(r.yieldUsableQuantity):'');useEffect(()=>setY(r.yieldUsableQuantity?String(r.yieldUsableQuantity):''),[r.yieldUsableQuantity,r.ingredientId]);const change=Number(r.changePct),dir=change>0.0001?'up':change< -0.0001?'down':'flat';return <div className={`pcs-row ${r.needsYieldSetup?'warn-row':''}`}><span><b>{r.ingredientName}</b><small>{r.supplier||'ShelfSense'} · {r.priceDate||'—'}</small></span><span><b>{r.sourceUnitCost!=null?`${money(r.sourceUnitCost)} / ${r.sourceBaseUnit}`:'—'}</b><small>{r.purchasePrice!=null?`${money(r.purchasePrice)} / ${qty(r.purchaseQuantity)} ${r.purchaseUnit}`:'No receipt value'}</small></span><span><b>{r.previousCostingRate!=null?`${money(r.previousCostingRate)} / ${r.costingUnit}`:'—'}</b><small>Published / current</small></span><span><b className={dir}>{dir==='up'?'↑ ':dir==='down'?'↓ ':''}{r.changePct!=null?pct(r.changePct):'New'}</b><small>{r.costingRate!=null?`${money(r.costingRate)} / ${r.costingUnit}`:'Cost unavailable'}</small></span><span>{r.needsYieldSetup?<div className="pcs-yield"><label>1 {r.yieldSourceUnit||r.sourceBaseUnit||r.purchaseUnit} =</label><input type="number" step="any" min="0" value={y} onChange={e=>setY(e.target.value)} placeholder="usable"/><em>{r.yieldCostingUnit||r.costingUnit}</em><button disabled={busy||!(Number(y)>0)} onClick={()=>onYield(r,y)}>Save</button></div>:<><b>{r.yieldUsableQuantity?`1 ${r.yieldSourceUnit||r.sourceBaseUnit} = ${qty(r.yieldUsableQuantity)} ${r.yieldCostingUnit}`:'Direct'}</b><small>{r.yieldUsableQuantity?'Saved usable yield':'No yield setup needed'}</small></>}</span><span><b>{r.conversionWarning?'Check source':r.needsYieldSetup?'Needs yield':r.changed?'Changed':'Unchanged'}</b>{r.conversionWarning?<small><button className="link" onClick={()=>onManual(r.ingredientId)}>Use manual</button></small>:null}</span></div>}

function History({snapshots,busy,onAction}){const [selected,setSelected]=useState(null);const shown=selected||snapshots[0];const menu=shown?.lines?.filter(x=>x.entity_type==='menu')||[];return <div className="pcs-history"><aside><h3>Costing versions</h3><p>Current plus recent history. Older snapshots remain preserved.</p>{snapshots.map((s,i)=><button key={s.id} className={(shown?.id===s.id?'active ':'')+s.status} onClick={()=>setSelected(s)}><b>{new Date(s.snapshot_date).toLocaleDateString()}</b><span>{s.status==='published'?'Active':s.status==='draft'?'Draft review':'Archived'}</span><small>{s.summary?.changed||0} ingredient changes · {s.summary?.menuCritical||0} critical</small></button>)}</aside><section>{!shown?<div className="pcs-empty">No costing snapshots yet. Create a ShelfSense review snapshot first.</div>:<><div className="pcs-history-head"><div><span>{shown.status.toUpperCase()}</span><h3>{new Date(shown.snapshot_date).toLocaleDateString()} Costing</h3><p>{shown.summary?.increased||0} increased · {shown.summary?.decreased||0} decreased · {shown.summary?.unchanged||0} unchanged</p></div>{shown.status==='draft'?<button className="primary" data-safety-action="publish-costing" disabled={busy} onClick={()=>onAction(shown.id,'publish')}>Publish Costing</button>:shown.status==='archived'?<button className="ghost" data-safety-action="restore-costing" disabled={busy} onClick={()=>onAction(shown.id,'restore')}>Restore as Active</button>:<span className="pcs-active-pill">Active</span>}</div><div className="pcs-impact"><div><small>HEALTHY</small><b>{shown.summary?.menuHealthy||0}</b></div><div><small>WATCH</small><b>{shown.summary?.menuWatch||0}</b></div><div><small>CRITICAL</small><b>{shown.summary?.menuCritical||0}</b></div><div><small>INCOMPLETE</small><b>{shown.summary?.menuIncomplete||0}</b></div></div><div className="pcs-menu-list"><div className="pcs-menu-row head"><span>Menu Item</span><span>Cost</span><span>Food Cost</span><span>Contribution</span><span>Status</span></div>{menu.slice(0,80).map(m=><div className="pcs-menu-row" key={m.entity_id}><span><b>{m.entity_name}</b><small>{m.source_breakdown?.category||''}</small></span><span>{money(m.cost)}{m.source_breakdown?.previousCost!=null&&<small>{pct(m.source_breakdown?.changePct)} vs previous</small>}</span><span>{m.food_cost_percent!=null?pct(m.food_cost_percent):'—'}<small>Target {m.source_breakdown?.targetFoodCost||35}%</small></span><span>{m.contribution!=null?money(m.contribution):'—'}</span><span className={`health ${m.source_breakdown?.status||''}`}>{m.source_breakdown?.status||'—'}</span></div>)}</div></>}</section></div>}

function Mappings({integration,bootstrap,busy,onManual}){const mapped=new Set((integration?.mappings||[]).map(x=>String(x.ingredient_id))),unmapped=(bootstrap?.ingredients||[]).filter(i=>!mapped.has(String(i.id)));return <div className="pcs-mapping"><div className="pcs-review-top"><div><h3>Ingredient mappings</h3><p>ShelfSense remains the source for purchase and storage cost. PlateCost owns yield and recipe costing.</p></div></div><div className="pcs-map-list">{(integration?.mappings||[]).map(m=><div key={m.ingredient_id}><span><b>{m.ingredient_name}</b><small>PlateCost</small></span><span>→</span><span><b>{m.external_item_name||'ShelfSense item'}</b><small>ShelfSense</small></span><button disabled={busy} onClick={()=>onManual(m.ingredient_id)}>Use Manual</button></div>)}</div>{unmapped.length>0&&<p className="pcs-note">{unmapped.length} ingredients are currently manual or unmapped.</p>}</div>}
